(function() {
	// Create the jstylerSliderJS plugin
	tinymce.create('tinymce.plugins.jstylerSliderJS', {
		init: function(ed, url) {
			var self = this;
			
			// Register the mceLaunchPopupJstylerSliderJS command
			// Launch a popup window that contains the form
			ed.addCommand('mceLaunchPopupJstylerSliderJS', function() {
				ed.windowManager.open({
					file: url + '/jstylerSliderJS_popup.php',
					width: 502,
					height: 200,
					inline: 1
				}, {
					plugin_url: url
				});
			});
			
			// Register the mceInsertShortcodeJstylerSliderJS command
			// Insert a shortcode generated by the data submitted from the form
			ed.addCommand('mceInsertShortcodeJstylerSliderJS', function(content) {
				var self = this;
				var shortcode = '[jstylerSliderJS settings="' + content + '"]<br/>';
				self.execCommand('mceInsertContent', false, shortcode);
				self.addVisual();
			});
	        
			// Register the button
			ed.addButton('jstylerSliderJS', {
				title : 'jstylerSliderJS_dlg.description',
				cmd : 'mceLaunchPopupJstylerSliderJS',
				image : url + '/img/icon.png'
			});
		}
	});
	
	// Register the plugin
	tinymce.PluginManager.add('jstylerSliderJS', tinymce.plugins.jstylerSliderJS);
})();